version: "3.9"
services:
  devsuApiBancario:
    image: postgres:15.1
    ports:
      - "5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: devsudb